source 'http://rubygems.org'

gem 'rails', '3.2.1'
gem 'pg'
gem 'newrelic_rpm'

gem 'active_link_to'
gem 'airbrake'
gem 'ancestry'
gem 'auditor'
gem 'cancan'
gem 'carrierwave'
gem 'daemons'
gem 'delayed_job_active_record'
gem 'devise'
gem 'devise-russian'
gem 'flash_messages_helper'
gem 'geocoder'
gem 'haml-rails'
gem 'high_voltage'
gem 'hominid'
gem 'inherited_resources'
gem 'jquery-rails'
gem 'kaminari'
gem 'koala'
gem 'meta-tags', :require => 'meta_tags'
gem 'mini_magick'
gem 'omniauth-facebook'
gem 'omniauth-vkontakte'
gem 'pjax_rails'
gem 'plist'
gem 'rails_config'
gem 'russian'
gem 'simple_form'
gem 'unicorn'
gem 'vk-ruby'
gem 'yajl-ruby'

group :assets do
  gem 'coffee-rails', '~> 3.2.1'
  gem 'compass-rails'
  gem 'execjs'
  gem 'sass-rails',   '~> 3.2.3'
  gem 'therubyracer'
  gem 'uglifier', '>= 1.0.3'
end

group :development do
  gem 'annotate', :git => 'git://github.com/ctran/annotate_models.git'
  gem 'awesome_print'
  gem 'capistrano'
  gem 'capistrano-ext'
  gem 'erb2haml'
  gem 'guard'
  gem 'guard-bundler'
  gem 'guard-migrate'
  gem 'guard-rspec'
  gem 'guard-spork'
  gem 'letter_opener'
  gem 'rails-footnotes', '>= 3.7.5.rc4'
  gem 'rb-fsevent'
  gem 'ruby_gntp' # for Growl notifications, works only with Growl >= 1.3
  gem 'yard'
end

group :development, :test do
  gem 'capybara', git: 'https://github.com/jnicklas/capybara.git'
  gem 'database_cleaner'
  gem 'fabrication'
  gem 'ffaker'
  gem 'fuubar'
  gem 'rspec-rails'
  gem 'spork', '> 0.9.0.rc'
  gem 'steak'
  gem 'timecop'
end